import React, { useState, useEffect, useRef } from 'react';
import AppLayout from '../components/layout/AppLayout';
import API from '../utils/api';
import { toast } from 'react-toastify';
import { shareOnWhatsApp } from '../utils/exportUtils';
import { useReactToPrint } from 'react-to-print';

const FeeReceipt = React.forwardRef(({ receipt }, ref) => (
  <div ref={ref} style={{padding:'32px', fontFamily:'Plus Jakarta Sans, sans-serif', maxWidth:'600px', margin:'0 auto'}}>
    <div style={{textAlign:'center', borderBottom:'2px solid #1e40af', paddingBottom:'16px', marginBottom:'20px'}}>
      <h1 style={{fontSize:'22px', fontWeight:'800', color:'#1e40af'}}>🏫 SchoolMS</h1>
      <p style={{fontSize:'13px', color:'#64748b'}}>Fee Payment Receipt</p>
    </div>
    <div style={{display:'flex', justifyContent:'space-between', marginBottom:'16px'}}>
      <div><strong>Receipt No:</strong> {receipt?.receipt_no}</div>
      <div><strong>Date:</strong> {receipt?.payment_date?.split('T')[0]}</div>
    </div>
    <table style={{width:'100%', borderCollapse:'collapse', marginBottom:'20px'}}>
      <tbody>
        {[
          ['Student Name', receipt?.full_name],
          ['Roll No', receipt?.roll_no],
          ['Class', receipt?.class_name],
          ['Fee Type', receipt?.fee_type_name],
          ['Month', receipt?.payment_month],
          ['Payment Method', receipt?.payment_method || '—'],
          ['Amount', `Rs. ${receipt?.amount}`],
          ...(receipt?.remarks ? [['Remarks', receipt.remarks]] : [])
        ].map(([k, v]) => (
          <tr key={k}>
            <td style={{padding:'8px', borderBottom:'1px solid #e2e8f0', color:'#64748b', width:'40%'}}>{k}</td>
            <td style={{padding:'8px', borderBottom:'1px solid #e2e8f0', fontWeight:'600'}}>{v}</td>
          </tr>
        ))}
      </tbody>
    </table>
    <div style={{background:'#f0fdf4', border:'1px solid #bbf7d0', borderRadius:'8px', padding:'16px', textAlign:'center'}}>
      <div style={{fontSize:'24px', fontWeight:'800', color:'#16a34a'}}>Rs. {receipt?.amount}</div>
      <div style={{fontSize:'12px', color:'#64748b'}}>Amount Received</div>
    </div>
    <div style={{marginTop:'32px', textAlign:'center', fontSize:'11px', color:'#94a3b8'}}>
      Thank you for your payment • Generated by {receipt?.generated_by_name}
    </div>
  </div>
));

const emptyForm = {
  student_id: '', fee_type_id: '', amount: '',
  payment_date: new Date().toISOString().split('T')[0],
  payment_month: '', payment_method: 'Cash',
  class_id: '', remarks: ''
};

const Fees = () => {
  const [payments, setPayments] = useState([]);
  const [students, setStudents] = useState([]);
  const [allStudents, setAllStudents] = useState([]);
  const [feeTypes, setFeeTypes] = useState([]);
  const [classes, setClasses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [saving, setSaving] = useState(false);
  const [search, setSearch] = useState('');
  const [receipt, setReceipt] = useState(null);
  const [showReceipt, setShowReceipt] = useState(false);
  const receiptRef = useRef();

  // RESTORED ORIGINAL PRINT ENGINE UNTOUCHED
  const printReceipt = useReactToPrint({ content: () => receiptRef.current });

  // SAFE TITLE OVERRIDE ADD-ON FOR DIRECT CAPACITOR DOWNLOAD
  const handlePrintAndSave = () => {
    const originalTitle = document.title;
    if (receipt && receipt.receipt_no) {
      document.title = `Fee-Receipt-${receipt.receipt_no}`;
    }
    printReceipt();
    setTimeout(() => {
      document.title = originalTitle;
    }, 1000);
  };

  const fetchAll = async () => {
    setLoading(true);
    try {
      const params = {};
      if (search) params.search = search;
      const [paymentsRes, studentsRes, feeTypesRes, classesRes] = await Promise.all([
        API.get('/fees', { params }),
        API.get('/students'),
        API.get('/config/fee-types'),
        API.get('/config/classes')
      ]);
      setPayments(paymentsRes.data);
      setAllStudents(studentsRes.data);
      setStudents(studentsRes.data);
      setFeeTypes(feeTypesRes.data);
      setClasses(classesRes.data);
    } catch (err) { toast.error('Failed to load data'); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchAll(); }, [search]);

  useEffect(() => {
    if (form.class_id) {
      setStudents(allStudents.filter(s => s.class_id == form.class_id));
      setForm(f => ({ ...f, student_id: '' }));
    } else {
      setStudents(allStudents);
    }
  }, [form.class_id, allStudents]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const { data } = await API.post('/fees', form);
      toast.success(`Fee recorded! Receipt: ${data.receipt_no}`);
      setShowModal(false);
      setForm(emptyForm);
      fetchAll();
    } catch (err) { toast.error(err.response?.data?.message || 'Failed'); }
    finally { setSaving(false); }
  };

  const viewReceipt = async (id) => {
    try {
      const { data } = await API.get(`/fees/receipt/${id}`);
      setReceipt(data);
      setShowReceipt(true);
    } catch (err) { toast.error('Failed to load receipt'); }
  };

  const shareWhatsApp = (p) => {
    const msg = `Dear ${p.full_name},\n\nYour fee payment of Rs.${p.amount} for ${p.fee_type_name} has been received.\nReceipt No: ${p.receipt_no}\nClass: ${p.class_name}\nPayment Method: ${p.payment_method || 'N/A'}\nDate: ${p.payment_date?.split('T')[0]}\n\nThank you - SchoolMS`;
    shareOnWhatsApp(p.phone, msg);
  };

  const paymentMethods = ['Cash', 'UPI', 'Account Transfer'];

  return (
    <AppLayout title="Fee Payment" subtitle="Manage student fee payments">
      <div className="page-header">
        <div><h1>Fee Payments</h1><p>{payments.length} records</p></div>
        <button className="btn btn-primary" onClick={() => { setShowModal(true); setForm(emptyForm); }}>
          💰 Add Fee Payment
        </button>
      </div>

      <div className="filter-bar">
        <input className="form-control search-input" placeholder="🔍 Search by name or roll no..." value={search} onChange={e => setSearch(e.target.value)} />
      </div>

      <div className="card">
        <div className="table-wrapper">
          {loading ? <div className="loading"><div className="spinner"></div></div> : (
            <table>
              <thead>
                <tr>
                  <th>Receipt No</th><th>Student</th><th>Class</th>
                  <th>Fee Type</th><th>Method</th><th>Amount</th>
                  <th>Date</th><th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {payments.map(p => (
                  <tr key={p.id}>
                    <td>
                      <code style={{fontFamily:'JetBrains Mono', fontSize:'12px', background:'#f1f5f9', padding:'2px 6px', borderRadius:'4px'}}>
                        {p.receipt_no}
                      </code>
                    </td>
                    <td><strong>{p.full_name}</strong><br/><small style={{color:'#64748b'}}>{p.roll_no}</small></td>
                    <td>{p.class_name}</td>
                    <td><span className="badge badge-info">{p.fee_type_name}</span></td>
                    <td>
                      <span className={"badge " + (
                        p.payment_method === 'Cash' ? 'badge-success' :
                        p.payment_method === 'UPI' ? 'badge-info' : 'badge-warning'
                      )}>
                        {p.payment_method || 'Cash'}
                      </span>
                    </td>
                    <td><strong style={{color:'#16a34a'}}>Rs. {parseFloat(p.amount).toLocaleString()}</strong></td>
                    <td>{p.payment_date?.split('T')[0]}</td>
                    <td>
                      <div style={{display:'flex', gap:'6px'}}>
                        <button className="btn btn-outline btn-sm" onClick={() => viewReceipt(p.id)}>👁️ View</button>
                        <button className="btn btn-whatsapp btn-sm" onClick={() => shareWhatsApp(p)}>
                          Share
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()} style={{maxWidth:'680px'}}>
            <div className="modal-header">
              <h2>💰 Add Fee Payment</h2>
              <button className="modal-close" onClick={() => setShowModal(false)}>✕</button>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="modal-body">
                <div className="form-grid">
                  <div className="form-group">
                    <label>Class <span>*</span></label>
                    <select className="form-control" value={form.class_id} onChange={e => setForm({...form, class_id: e.target.value})} required>
                      <option value="">Select Class</option>
                      {classes.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Student <span>*</span></label>
                    <select className="form-control" value={form.student_id} onChange={e => setForm({...form, student_id: e.target.value})} required disabled={!form.class_id}>
                      <option value="">{form.class_id ? 'Select Student' : 'Select class first'}</option>
                      {students.map(s => <option key={s.id} value={s.id}>{s.full_name} ({s.roll_no})</option>)}
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Fee Type <span>*</span></label>
                    <select className="form-control" value={form.fee_type_id} onChange={e => setForm({...form, fee_type_id: e.target.value})} required>
                      <option value="">Select Fee Type</option>
                      {feeTypes.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Payment Method <span>*</span></label>
                    <select className="form-control" value={form.payment_method} onChange={e => setForm({...form, payment_method: e.target.value})} required>
                      {paymentMethods.map(m => <option key={m} value={m}>{m}</option>)}
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Amount (Rs.) <span>*</span></label>
                    <input type="number" className="form-control" value={form.amount} onChange={e => setForm({...form, amount: e.target.value})} required placeholder="0.00" />
                  </div>
                  <div className="form-group">
                    <label>Payment Date <span>*</span></label>
                    <input type="date" className="form-control" value={form.payment_date} onChange={e => setForm({...form, payment_date: e.target.value})} required />
                  </div>
                  <div className="form-group">
                    <label>Payment Month</label>
                    <input type="month" className="form-control" value={form.payment_month} onChange={e => setForm({...form, payment_month: e.target.value})} />
                  </div>
                  <div className="form-group">
                    <label>Remarks</label>
                    <input className="form-control" value={form.remarks} onChange={e => setForm({...form, remarks: e.target.value})} placeholder="Optional remarks" />
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-outline" onClick={() => setShowModal(false)}>Cancel</button>
                <button type="submit" className="btn btn-primary" disabled={saving}>{saving ? '⏳ Saving...' : '💾 Save Receipt'}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {showReceipt && receipt && (
        <div className="modal-overlay" onClick={() => setShowReceipt(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header no-print">
              <h2>🧾 Fee Receipt</h2>
              <div style={{display:'flex', gap:'8px'}}>
                {/* WHATSAPP SHARE IS FULLY RESTORED AND SAVING ROUTE ENHANCED */}
                <button className="btn btn-primary btn-sm" onClick={handlePrintAndSave}>🖨️ Print / Download PDF</button>
                <button className="btn btn-whatsapp btn-sm" onClick={() => shareOnWhatsApp(
                  receipt.phone,
                  `Fee Receipt - ${receipt.receipt_no}\nStudent: ${receipt.full_name}\nClass: ${receipt.class_name}\nAmount: Rs.${receipt.amount}`
                )}>Share</button>
                <button className="modal-close" onClick={() => setShowReceipt(false)}>✕</button>
              </div>
            </div>
            <FeeReceipt receipt={receipt} />
          </div>
        </div>
      )}
    </AppLayout>
  );
};

export default Fees;