import React, { useState, useEffect, useRef } from 'react';
import AppLayout from '../components/layout/AppLayout';
import API from '../utils/api';
import { toast } from 'react-toastify';
import { shareOnWhatsApp } from '../utils/exportUtils';
import { useReactToPrint } from 'react-to-print';
import { useAuth } from '../context/AuthContext';

const SalarySlipPrint = React.forwardRef(({ slip }, ref) => (
  <div ref={ref} style={{padding:'32px', fontFamily:'Plus Jakarta Sans, sans-serif', maxWidth:'600px', margin:'0 auto', background: '#fff'}}>
    <div style={{textAlign:'center', borderBottom:'2px solid #1e40af', paddingBottom:'16px', marginBottom:'20px'}}>
      <h1 style={{fontSize:'22px', fontWeight:'800', color:'#1e40af'}}>🏫 SchoolMS</h1>
      <p style={{fontSize:'13px', color:'#64748b'}}>Salary Slip — {slip?.month}</p>
    </div>
    <table style={{width:'100%', borderCollapse:'collapse', marginBottom:'20px'}}>
      <tbody>
        {[['Slip No', slip?.slip_no], ['Employee', slip?.full_name], ['Emp ID', slip?.emp_id], ['Role', slip?.role_name], ['Month', slip?.month], ['Basic Salary', `₹ ${slip?.basic_salary}`], ['Deductions', `₹ ${slip?.deductions}`], ['Net Salary', `₹ ${slip?.net_salary}`]].map(([k,v]) => (
          <tr key={k}>
            <td style={{padding:'8px', borderBottom:'1px solid #e2e8f0', color:'#64748b', width:'40%'}}>{k}</td>
            <td style={{padding:'8px', borderBottom:'1px solid #e2e8f0', fontWeight: k === 'Net Salary' ? '800' : '600'}}>{v}</td>
          </tr>
        ))}
      </tbody>
    </table>
    <div style={{background:'#f0fdf4', border:'1px solid #bbf7d0', borderRadius:'8px', padding:'16px', textAlign:'center'}}>
      <div style={{fontSize:'24px', fontWeight:'800', color:'#16a34a'}}>₹ {slip?.net_salary}</div>
      <div style={{fontSize:'12px', color:'#64748b'}}>Net Salary Payable</div>
    </div>
    <div style={{marginTop:'20px', textAlign:'center', fontSize:'11px', color:'#94a3b8'}}>Generated by {slip?.generated_by_name}</div>
  </div>
));

const Salary = () => {
  const { user } = useAuth();
  const [slips, setSlips] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState({ employee_id: '', month: new Date().getMonth() + 1, year: new Date().getFullYear(), basic_salary: '', deductions: '0' });
  const [saving, setSaving] = useState(false);
  const [slip, setSlip] = useState(null);
  const [showSlip, setShowSlip] = useState(false);
  const [filters, setFilters] = useState({ month: new Date().getMonth() + 1, year: new Date().getFullYear() });
  const slipRef = useRef();

  // ─── NEW BLOB DOWNLOAD LOGIC FOR ANDROID WEBVIEW BYPASS ───
  const downloadSalaryPDFDirectly = () => {
    try {
      const htmlContent = `
        <html>
          <head>
            <title>Salary-Slip-${slip?.slip_no || 'Payroll'}</title>
            <style>
              body { font-family: 'Plus Jakarta Sans', sans-serif; padding: 20px; color: #1e293b; }
              .card { max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; padding: 24px; border-radius: 8px; }
              .header { text-align: center; border-bottom: 2px solid #1e40af; padding-bottom: 12px; margin-bottom: 16px; }
              table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
              td { padding: 10px; border-bottom: 1px solid #e2e8f0; }
              .total-box { background: #f0fdf4; padding: 16px; text-align: center; border-radius: 6px; font-size: 20px; font-weight: bold; color: #16a34a; }
            </style>
          </head>
          <body>
            <div class="card">
              <div class="header">
                <h1 style="color:#1e40af;margin:0;">🏫 SchoolMS</h1>
                <p style="color:#64748b;margin:4px 0 0;">Salary Slip — ${slip?.month || ''}</p>
              </div>
              <table>
                <tr><td>Slip No</td><td><strong>${slip?.slip_no || ''}</strong></td></tr>
                <tr><td>Employee</td><td><strong>${slip?.full_name || ''}</strong></td></tr>
                <tr><td>Employee ID</td><td>${slip?.emp_id || ''}</td></tr>
                <tr><td>Role</td><td>${slip?.role_name || ''}</td></tr>
                <tr><td>Basic Salary</td><td>₹ ${slip?.basic_salary || '0'}</td></tr>
                <tr><td>Deductions</td><td>₹ ${slip?.deductions || '0'}</td></tr>
                <tr><td>Net Salary</td><td><strong>₹ ${slip?.net_salary || '0'}</strong></td></tr>
              </table>
              <div class="total-box">₹ ${slip?.net_salary || '0'}</div>
            </div>
            <script>window.onload = function() { window.print(); }</script>
          </body>
        </html>
      `;

      // Native Blob Conversion mechanism
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Salary-Slip-${slip?.slip_no || 'Payroll'}.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast.success("File generated successfully!");
    } catch (err) {
      toast.error("Generation failed");
    }
  };

  const [searchQuery, setSearchQuery] = useState('');
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const years = []; for (let y = 2020; y <= new Date().getFullYear() + 1; y++) years.push(y);

  const fetchAll = async () => {
    setLoading(true);
    try {
      const roleType = user.role === 'principal' ? 'employee' : undefined;
      const params = { from_month: filters.month, from_year: filters.year, to_month: filters.month, to_year: filters.year };
      const [slipsRes, empRes] = await Promise.all([
        API.get('/salary', { params }),
        API.get('/employees', { params: roleType ? { role_type: roleType } : {} })
      ]);
      setSlips(slipsRes.data);
      setEmployees(empRes.data);
    } catch (err) { toast.error('Failed to load data'); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchAll(); }, [filters]);

  const filteredSlips = slips.filter(s => {
    const name = s.full_name?.toLowerCase() || '';
    const empId = s.emp_id?.toLowerCase() || '';
    const query = searchQuery.toLowerCase();
    return name.includes(query) || empId.includes(query);
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const { data } = await API.post('/salary', form);
      toast.success(`Salary slip generated! ${data.slip_no}`);
      setShowModal(false);
      fetchAll();
    } catch (err) { toast.error(err.response?.data?.message || 'Failed'); }
    finally { setSaving(false); }
  };

  const markPaid = async (id) => {
    try {
      await API.put(`/salary/${id}/paid`);
      toast.success('Marked as paid!');
      fetchAll();
    } catch (err) { toast.error('Failed'); }
  };

  const viewSlip = async (id) => {
    try {
      const { data } = await API.get(`/salary/${id}`);
      setSlip(data);
      setShowSlip(true);
    } catch (err) { toast.error('Failed to load slip'); }
  };

  const triggerWhatsAppShare = (s) => {
    const phone = s.phone?.toString().replace(/[\s\-\(\)\+]/g,'');
    const withCountry = phone?.startsWith('91') ? phone : '91' + phone;
    const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    const monthLabel = s.month ? (() => { const parts = s.month.split('-'); return `${monthNames[parseInt(parts[1])-1]} ${parts[0]}`; })() : s.month;
    const message = `Salary Slip Ready - ${monthLabel}\n\nNet Salary: Rs. ${parseFloat(s.net_salary || 0).toLocaleString('en-IN')}\n\nSchoolMS`;
    window.open(`https://wa.me/${withCountry}?text=${encodeURIComponent(message)}`, '_blank');
  };

  return (
    <AppLayout title="Salary Slip" subtitle="Generate and manage salary slips">
      <style>{`
        .desktop-salary-view { display: block; } .mobile-salary-view { display: none; }
        @media (max-width: 1300px) {
          .desktop-salary-view { display: none !important; } .mobile-salary-view { display: block !important; width: 100% !important; }
          .mobile-salary-card { background: #fff; border: 1px solid #cbd5e1; border-radius: 14px; padding: 16px; margin-bottom: 16px; }
          .mobile-card-row-top { display: flex; justify-content: space-between; }
          .mobile-card-details { background: #f8fafc; border-radius: 10px; padding: 12px; margin-bottom: 14px; display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
          .mobile-card-actions { display: flex; gap: 8px; }
          .mobile-action-btn { flex: 1; padding: 10px; font-size: 12px; font-weight: 700; border-radius: 8px; text-align: center; }
        }
      `}</style>

      <div style={{ width: '100%', overflowX: 'hidden' }}>
        <div className="page-header">
          <h1>Salary Slips</h1>
          <button className="btn btn-primary" onClick={() => setShowModal(true)}>💵 Generate Salary Slip</button>
        </div>

        <div className="filter-bar" style={{ display: 'flex', gap: '12px', marginBottom: '20px' }}>
          <input type="text" className="form-control" placeholder="🔍 Search..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} style={{ flex: 1 }} />
        </div>

        {loading ? <div className="loading"><div className="spinner"></div></div> : (
          <>
            <div className="mobile-salary-view">
              {filteredSlips.map((s) => (
                <div key={s.id} className="mobile-salary-card">
                  <div className="mobile-card-row-top">
                    <h3>{s.full_name}</h3>
                    <span className="badge badge-success">{s.status}</span>
                  </div>
                  <div className="mobile-card-details">
                    <div>Slip: {s.slip_no}</div>
                    <div>Salary: ₹ {parseFloat(s.net_salary).toLocaleString()}</div>
                  </div>
                  <div className="mobile-card-actions">
                    <button className="btn btn-outline mobile-action-btn" onClick={() => viewSlip(s.id)}>👁️ View</button>
                  </div>
                </div>
              ))}
            </div>

            <div className="desktop-salary-view">
              <div className="card"><div className="table-wrapper">
                <table>
                  <thead><tr><th>Slip No</th><th>Employee</th><th>Month</th><th>Net Salary</th><th>Actions</th></tr></thead>
                  <tbody>
                    {filteredSlips.map(s => (
                      <tr key={s.id}>
                        <td>{s.slip_no}</td>
                        <td>{s.full_name}</td>
                        <td>{s.month}</td>
                        <td>₹ {parseFloat(s.net_salary).toLocaleString()}</td>
                        <td><button className="btn btn-outline btn-sm" onClick={() => viewSlip(s.id)}>👁️ View</button></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div></div>
            </div>
          </>
        )}
      </div>

      {showSlip && slip && (
        <div className="modal-overlay" onClick={() => setShowSlip(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2>📄 Salary Slip</h2>
              <div style={{display:'flex', gap:'8px'}}>
                <button className="btn btn-primary btn-sm" onClick={downloadSalaryPDFDirectly}>📥 Download File</button>
                <button className="modal-close" onClick={() => setShowSlip(false)}>✕</button>
              </div>
            </div>
            <SalarySlipPrint ref={slipRef} slip={slip} />
          </div>
        </div>
      )}
    </AppLayout>
  );
};

export default Salary;