import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Capacitor } from '@capacitor/core';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { toast } from 'react-toastify';

const cleanText = (str) => {
  if (!str) return '';
  return String(str).replace(/[^\x20-\x7E]/g, '').trim();
};

const saveToDownloads = async (base64, fileName) => {
  await Filesystem.writeFile({
    path: `Download/${fileName}`,
    data: base64,
    directory: Directory.ExternalStorage,
    recursive: true,
  });
};

export const downloadFeeReceiptPDF = async (receipt) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a5' });
  doc.setFontSize(18); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 64, 175);
  doc.text('SchoolMS', 74, 16, { align: 'center' });
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 116, 139);
  doc.text('Fee Payment Receipt', 74, 22, { align: 'center' });
  doc.setDrawColor(30, 64, 175); doc.setLineWidth(0.5); doc.line(14, 26, 134, 26);
  doc.setFontSize(9); doc.setTextColor(0,0,0);
  doc.setFont('helvetica', 'bold');
  doc.text(`Receipt No: ${cleanText(receipt.receipt_no)}`, 14, 33);
  doc.text(`Date: ${receipt.payment_date?.split('T')[0] || ''}`, 134, 33, { align: 'right' });
  const rows = [
    ['Student Name', cleanText(receipt.full_name)],
    ['Roll No', cleanText(receipt.roll_no)],
    ['Class', cleanText(receipt.class_name)],
    ['Fee Type', cleanText(receipt.fee_type_name)],
    ['Month', cleanText(receipt.payment_month)],
    ['Payment Method', cleanText(receipt.payment_method) || 'Cash'],
    ['Amount', `Rs. ${receipt.amount}`],
  ];
  if (receipt.remarks) rows.push(['Remarks', cleanText(receipt.remarks)]);
  autoTable(doc, {
    body: rows, startY: 37,
    styles: { fontSize: 9, cellPadding: 4, font: 'helvetica' },
    columnStyles: { 0: { fontStyle: 'bold', textColor: [100,116,139], cellWidth: 45 }, 1: { fontStyle: 'bold' } },
    alternateRowStyles: { fillColor: [248,250,252] },
    margin: { left: 14, right: 14 },
  });
  const finalY = doc.lastAutoTable.finalY + 8;
  doc.setFillColor(240,253,244); doc.setDrawColor(187,247,208);
  doc.roundedRect(14, finalY, 120, 22, 3, 3, 'FD');
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(22,163,74);
  doc.text(`Rs. ${receipt.amount}`, 74, finalY + 11, { align: 'center' });
  doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(100,116,139);
  doc.text('Amount Received', 74, finalY + 17, { align: 'center' });
  doc.text(`Thank you for your payment - Generated by ${cleanText(receipt.generated_by_name)}`, 74, finalY + 28, { align: 'center' });
  const fileName = `Fee-Receipt-${cleanText(receipt.receipt_no)}.pdf`;
  if (Capacitor.isNativePlatform()) {
    toast.info(`Saving ${fileName}...`, { autoClose: 2000 });
    const base64 = doc.output('datauristring').split(',')[1];
    await saveToDownloads(base64, fileName);
    toast.success(`Saved to Downloads: ${fileName}`, { autoClose: 4000 });
  } else {
    doc.save(fileName);
  }
};

export const downloadSalarySlipPDF = async (slip) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a5' });
  doc.setFontSize(18); doc.setFont('helvetica','bold'); doc.setTextColor(30,64,175);
  doc.text('SchoolMS', 74, 16, { align: 'center' });
  doc.setFontSize(10); doc.setFont('helvetica','normal'); doc.setTextColor(100,116,139);
  doc.text(`Salary Slip - ${cleanText(slip.month)}`, 74, 22, { align: 'center' });
  doc.setDrawColor(30,64,175); doc.setLineWidth(0.5); doc.line(14, 26, 134, 26);
  const rows = [
    ['Slip No', cleanText(slip.slip_no)],
    ['Employee', cleanText(slip.full_name)],
    ['Emp ID', cleanText(slip.emp_id)],
    ['Role', cleanText(slip.role_name)],
    ['Month', cleanText(slip.month)],
    ['Basic Salary', `Rs. ${slip.basic_salary}`],
    ['Deductions', `Rs. ${slip.deductions}`],
    ['Net Salary', `Rs. ${slip.net_salary}`],
  ];
  autoTable(doc, {
    body: rows, startY: 32,
    styles: { fontSize: 9, cellPadding: 4, font: 'helvetica' },
    columnStyles: { 0: { fontStyle: 'bold', textColor: [100,116,139], cellWidth: 45 }, 1: { fontStyle: 'bold' } },
    alternateRowStyles: { fillColor: [248,250,252] },
    margin: { left: 14, right: 14 },
  });
  const finalY = doc.lastAutoTable.finalY + 8;
  doc.setFillColor(240,253,244); doc.setDrawColor(187,247,208);
  doc.roundedRect(14, finalY, 120, 22, 3, 3, 'FD');
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(22,163,74);
  doc.text(`Rs. ${slip.net_salary}`, 74, finalY + 11, { align: 'center' });
  doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(100,116,139);
  doc.text('Net Salary Payable', 74, finalY + 17, { align: 'center' });
  doc.text(`Generated by ${cleanText(slip.generated_by_name)}`, 74, finalY + 28, { align: 'center' });
  const fileName = `Salary-Slip-${cleanText(slip.slip_no)}.pdf`;
  if (Capacitor.isNativePlatform()) {
    toast.info(`Saving ${fileName}...`, { autoClose: 2000 });
    const base64 = doc.output('datauristring').split(',')[1];
    await saveToDownloads(base64, fileName);
    toast.success(`Saved to Downloads: ${fileName}`, { autoClose: 4000 });
  } else {
    doc.save(fileName);
  }
};