import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const cleanPhone = (phone) => {
  if (!phone) return null;
  let cleaned = phone.toString().replace(/[\s\-\(\)\+]/g, '');
  if (cleaned.startsWith('0')) cleaned = '91' + cleaned.slice(1);
  if (!cleaned.startsWith('91') && cleaned.length === 10) cleaned = '91' + cleaned;
  return cleaned;
};

// ─── FEE RECEIPT PDF GENERATOR ───────────────────────────────
export const generateFeeReceiptPDF = (receipt) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a5' });

  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, 148, 32, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('SchoolMS', 10, 13);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Fee Payment Receipt', 10, 21);
  doc.text(`Receipt No: ${receipt.receipt_no}`, 10, 28);
  doc.text(`Date: ${receipt.payment_date?.split('T')[0] || ''}`, 138, 28, { align: 'right' });

  doc.setTextColor(0, 0, 0);

  autoTable(doc, {
    startY: 40,
    head: [],
    body: [
      ['Student Name', receipt.full_name || '—'],
      ['Roll No', receipt.roll_no || '—'],
      ['Class', receipt.class_name || '—'],
      ['Fee Type', receipt.fee_type_name || '—'],
      ['Payment Month', receipt.payment_month || '—'],
      ['Payment Method', receipt.payment_method || 'Cash'],
      ['Remarks', receipt.remarks || '—'],
    ],
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [241, 245, 249], cellWidth: 48 },
      1: { cellWidth: 82 }
    },
    theme: 'grid',
    margin: { left: 10, right: 10 },
  });

  const finalY = doc.lastAutoTable.finalY + 8;
  doc.setFillColor(240, 253, 244);
  doc.setDrawColor(22, 163, 74);
  doc.setLineWidth(0.5);
  doc.roundedRect(10, finalY, 128, 18, 3, 3, 'FD');
  doc.setTextColor(22, 163, 74);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(
    `Amount Paid: Rs. ${parseFloat(receipt.amount || 0).toLocaleString('en-IN')}`,
    74, finalY + 11, { align: 'center' }
  );

  doc.setTextColor(148, 163, 184);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Thank you for your payment • Generated by SchoolMS', 74, finalY + 26, { align: 'center' });

  return doc;
};

// ─── SALARY SLIP PDF GENERATOR ───────────────────────────────
export const generateSalarySlipPDF = (slip) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a5' });

  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, 148, 32, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('SchoolMS', 10, 13);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Salary Slip', 10, 21);
  doc.text(`Slip No: ${slip.slip_no}`, 10, 28);
  doc.text(`Month: ${slip.month}`, 138, 28, { align: 'right' });

  doc.setTextColor(0, 0, 0);

  autoTable(doc, {
    startY: 40,
    head: [],
    body: [
      ['Employee Name', slip.full_name || '—'],
      ['Employee ID', slip.emp_id || '—'],
      ['Designation', slip.role_name || '—'],
      ['Month', slip.month || '—'],
    ],
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [241, 245, 249], cellWidth: 48 },
      1: { cellWidth: 82 }
    },
    theme: 'grid',
    margin: { left: 10, right: 10 },
  });

  const y1 = doc.lastAutoTable.finalY + 6;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Salary Breakdown', 10, y1);

  autoTable(doc, {
    startY: y1 + 4,
    head: [['Component', 'Amount (Rs.)']],
    body: [
      ['Basic Salary', `Rs. ${parseFloat(slip.basic_salary || 0).toLocaleString('en-IN')}`],
      ['Deductions', `- Rs. ${parseFloat(slip.deductions || 0).toLocaleString('en-IN')}`],
      ['Net Salary', `Rs. ${parseFloat(slip.net_salary || 0).toLocaleString('en-IN')}`],
    ],
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [30, 64, 175], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
    theme: 'grid',
    margin: { left: 10, right: 10 },
    didParseCell: (data) => {
      if (data.row.index === 2) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [240, 253, 244];
        data.cell.styles.textColor = [22, 163, 74];
      }
    }
  });

  const y2 = doc.lastAutoTable.finalY + 6;
  const isPaid = slip.status === 'paid';
  doc.setFillColor(isPaid ? 240 : 254, isPaid ? 253 : 243, isPaid ? 244 : 199);
  doc.setDrawColor(isPaid ? 22 : 217, isPaid ? 163 : 119, isPaid ? 74 : 6);
  doc.roundedRect(10, y2, 128, 12, 2, 2, 'FD');
  doc.setTextColor(isPaid ? 22 : 217, isPaid ? 163 : 119, isPaid ? 74 : 6);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  const statusLabel = 'DEPOSITED';
  doc.text(`Status: ${statusLabel}`, 74, y2 + 8, { align: 'center' });

  doc.setTextColor(148, 163, 184);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by SchoolMS • Computer Generated Document', 74, y2 + 22, { align: 'center' });

  return doc;
};

// ─── SHARE PDF ON WHATSAPP ────────────────────────────────────
// Step 1: Generate PDF → Save as file to device
// Step 2: Open WhatsApp Web with message
// Step 3: User attaches the downloaded PDF (standard web behavior)
const sharePDFOnWhatsApp = (doc, filename, phone, whatsappMessage) => {
  // Save PDF to device
  doc.save(filename);

  // Short delay then open WhatsApp
  setTimeout(() => {
    const cleaned = cleanPhone(phone);
    if (!cleaned) {
      alert('No WhatsApp number found. PDF has been downloaded.');
      return;
    }
    const encoded = encodeURIComponent(whatsappMessage);
    window.open(`https://wa.me/${cleaned}?text=${encoded}`, '_blank');
  }, 1500);
};

// ─── FEE RECEIPT: SHARE ON WHATSAPP ──────────────────────────
export const shareFeeReceiptWhatsApp = (receipt, phone) => {
  const doc = generateFeeReceiptPDF(receipt);
  const filename = `Fee-Receipt-${receipt.receipt_no}.pdf`;

  const message =
    `🏫 *SchoolMS - Fee Payment Receipt*\n\n` +
    `✅ Payment received successfully!\n\n` +
    `📋 *Receipt No:* ${receipt.receipt_no}\n` +
    `👤 *Student:* ${receipt.full_name}\n` +
    `🏫 *Class:* ${receipt.class_name}\n` +
    `📚 *Fee Type:* ${receipt.fee_type_name}\n` +
    `💵 *Amount Paid:* Rs. ${parseFloat(receipt.amount || 0).toLocaleString('en-IN')}\n` +
    `💳 *Payment Method:* ${receipt.payment_method || 'Cash'}\n` +
    `📅 *Date:* ${receipt.payment_date?.split('T')[0]}\n\n` +
    `📎 *PDF receipt "${filename}" has been saved to your device.*\n` +
    `Please attach it to this chat if needed.\n\n` +
    `_SchoolMS - School Management System_`;

  sharePDFOnWhatsApp(doc, filename, phone, message);
};

// ─── SALARY SLIP: SHARE ON WHATSAPP ──────────────────────────
export const shareSalarySlipWhatsApp = (slip, phone, email) => {
  const doc = generateSalarySlipPDF(slip);
  doc.save(`Salary-Slip-${slip.slip_no}-${slip.month}.pdf`);

  setTimeout(() => {
    const cleaned = cleanPhone(phone);
    if (!cleaned) {
      alert('No WhatsApp number found. PDF has been downloaded.');
      return;
    }

    const message =
      `📋 *Salary Slip Ready - ${slip.month}*\n\n` +
      `Dear *${slip.full_name}*, your salary slip for *${slip.month}* is ready!\n\n` +
      `💰 *Net Salary: Rs. ${parseFloat(slip.net_salary || 0).toLocaleString('en-IN')}*\n\n` +
      `📧 Please check your email ${email ? `(*${email}*)` : ''} for the PDF.\n\n` +
      `_SchoolMS - School Management System_`;

    const encoded = encodeURIComponent(message);
    window.open(`https://wa.me/${cleaned}?text=${encoded}`, '_blank');
  }, 1500);
};